Refer to `::core::option::Option` explicitly
duchess-rs/duchess pull request #109
Opened 2023-07-28 13:11 UTC by Aurel300

Fixes #108.

This can/should probably be taken further: the declared types are still referred to using relative names, and there could still be clashes with e.g. the `Local` type.

2023-08-02 09:07 UTC, fpoli requested changes
Could you declare `scala.Option` in `test-crates/viper/src/lib.rs` to avoid future regressions?

2023-08-02 11:33 UTC, fpoli approved these changes
Thanks!

2023-08-02 11:49 UTC, Aurel300 commented
Ah, of course, adding `scala.Option` to the test crate means we need #102.

2023-08-02 13:32 UTC, fpoli commented
> Ah, of course, adding `scala.Option` to the test crate means we need #102.

Oh, I didn't foresee that. If you want to remove the `scala.Option` we can merge immediately; the changes are small anyway. Otherwise, we'll wait for #102.

2023-08-02 15:54 UTC, Aurel300 commented
Ok, I removed `scala.Option`—let's add that in #102. For now this tests at least that `Result` is not clashing.

2023-08-03 07:28 UTC, fpoli approved these changes

2023-08-03 07:29 UTC, merged